STARTMARKER = 60 # "<"
ENDMARKER = 62  # ">"
ENDIAN = "little" # little/big
ACKNOWLEDGEMENT_SUCCESS = 0
ACKNOWLEDGEMENT_FAIL = 1
COMM_MODE_SEND = 1
COMM_MODE_RECEIVE = 0
TIMEOUT = 0.15
SERIAL_PORT = "/dev/ttyUSB1"
BAUD_RATE = 19200

# tasks
# comms
COMMS = 1
COMMS_TASK1 = 10

# sensors
SENSOR_PACKET_LENGTH = 15
SENSOR_MODE = 2
SENSOR_DATA_REQ = 20

# motors
MOTOR = 3
MOTOR_MOVE = 30
MOTOR_TURN = 31
MOTOR_VELOCITY_REQ = 32  