project_name: CustomNetV2
experiment_name: two_adam_80_default
dataset:
  dataset_path: D:\Wei_Xiong\projects\table-navigation\data
  targets:
  - no_objects
  - left
  - middle
  - right
  - all
  - left_mid
  - right_mid
  image_size:
  - 96
  - 320
  subset: -1
random_seed: 42
device: cuda
model:
  name: 'CustomNetV2'  # 'MobileNetV3_large' or 'AlexNet' or 'WinsonNet'
  pretrained: False
  freezed: False
  start_epoch: 0
  full_frame: False
optimizer:
  optimizer: sgd # adam, sgd, rmsprop
  lr: 0.003
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 350
  num_workers: 16
  train_batch_size: 32
  validation_batch_size: 32
  early_stopping: 10
  dropout: 0.2
metric_params:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall']
  average: 'weighted'
