project_name: CustomNetV2
experiment_name: ten_rmsprop_100
dataset:
  dataset_path: D:\Wei_Xiong\projects\table-navigation\data
  targets:
  - no_objects
  - left
  - middle
  - right
  - all
  - left_mid
  - right_mid
  image_size:
  - 320
  - 96
  subset: -1
random_seed: 42
device: cuda
model:
  name: CustomNetV2
  pretrained: false
  freezed: false
  start_epoch: 0
  full_frame: false
optimizer:
  optimizer: rmsprop
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
scheduler:
  start_factor: 0.001
train_params:
  epochs: 100
  num_workers: 16
  train_batch_size: 32
  validation_batch_size: 32
  early_stopping: 10
  dropout: 0.4
metric_params:
  metrics:
  - accuracy
  - f1_score
  - precision
  - recall
  average: weighted
