STARTMARKER = 60 # "<"
ENDMARKER = 62  # ">"
ENDIAN = "little" # little/big
ACKNOWLEDGEMENT_SUCCESS = 0
ACKNOWLEDGEMENT_FAIL = 1
COMM_MODE_SEND = 1
COMM_MODE_RECEIVE = 0
TIMEOUT = 5
SERIAL_PORT = "ACMUSB0"
BAUD_RATE = 9600

# tasks
# comms
COMMS = 1
COMMS_TASK1 = 10

# sensors
SENSOR_MODE = 2
SENSOR_DATA_REQ = 20

# motors
MOTOR = 3
MOTOR_MOVE = 30
MOTOR_TURN = 31
MOTOR_VELOCITY_REQ = 32  